# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyText(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SpamType:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyText", llm_response=llm_response, mode="request")
        return typing.cast(types.SpamType, result)

    def ClassifyTicket(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List[types.TicketLabel]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyTicket", llm_response=llm_response, mode="request")
        return typing.cast(typing.List[types.TicketLabel], result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="request")
        return typing.cast(types.Resume, result)

    def GetOrderInfo(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.OrderInfo:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GetOrderInfo", llm_response=llm_response, mode="request")
        return typing.cast(types.OrderInfo, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyText(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SpamType:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyText", llm_response=llm_response, mode="stream")
        return typing.cast(types.SpamType, result)

    def ClassifyTicket(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List[types.TicketLabel]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyTicket", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List[types.TicketLabel], result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Resume, result)

    def GetOrderInfo(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.OrderInfo:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GetOrderInfo", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.OrderInfo, result)

    