# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class Email(BaseModel):
    subject: typing.Optional[str] = None
    body: typing.Optional[str] = None
    from_address: typing.Optional[str] = None

class OrderInfo(BaseModel):
    order_status: typing.Optional[typing.Union[str, str, str, str]] = None
    tracking_number: typing.Optional[str] = None
    estimated_delivery_date: typing.Optional[str] = None

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

class TicketClassification(BaseModel):
    labels: typing.List[types.TicketLabel]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
