# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def ClassifyText(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SpamType:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="ClassifyText", args={
            "input": input,
        })
        return typing.cast(types.SpamType, result.cast_to(types, types, stream_types, False, __runtime__))
    def ClassifyTicket(self, ticket: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List[types.TicketLabel]:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="ClassifyTicket", args={
            "ticket": ticket,
        })
        return typing.cast(typing.List[types.TicketLabel], result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractResume", args={
            "resume": resume,
        })
        return typing.cast(types.Resume, result.cast_to(types, types, stream_types, False, __runtime__))
    def GetOrderInfo(self, email: types.Email,
        baml_options: BamlCallOptions = {},
    ) -> types.OrderInfo:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="GetOrderInfo", args={
            "email": email,
        })
        return typing.cast(types.OrderInfo, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyText(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[types.SpamType, types.SpamType]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ClassifyText", args={
            "input": input,
        })
        return baml_py.BamlSyncStream[types.SpamType, types.SpamType](
          result,
          lambda x: typing.cast(types.SpamType, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SpamType, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ClassifyTicket(self, ticket: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List[types.TicketLabel], typing.List[types.TicketLabel]]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ClassifyTicket", args={
            "ticket": ticket,
        })
        return baml_py.BamlSyncStream[typing.List[types.TicketLabel], typing.List[types.TicketLabel]](
          result,
          lambda x: typing.cast(typing.List[types.TicketLabel], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List[types.TicketLabel], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Resume, types.Resume]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractResume", args={
            "resume": resume,
        })
        return baml_py.BamlSyncStream[stream_types.Resume, types.Resume](
          result,
          lambda x: typing.cast(stream_types.Resume, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Resume, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GetOrderInfo(self, email: types.Email,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.OrderInfo, types.OrderInfo]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="GetOrderInfo", args={
            "email": email,
        })
        return baml_py.BamlSyncStream[stream_types.OrderInfo, types.OrderInfo](
          result,
          lambda x: typing.cast(stream_types.OrderInfo, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.OrderInfo, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyText(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyText", args={
            "input": input,
        }, mode="request")
        return result
    def ClassifyTicket(self, ticket: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyTicket", args={
            "ticket": ticket,
        }, mode="request")
        return result
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="request")
        return result
    def GetOrderInfo(self, email: types.Email,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetOrderInfo", args={
            "email": email,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyText(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyText", args={
            "input": input,
        }, mode="stream")
        return result
    def ClassifyTicket(self, ticket: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyTicket", args={
            "ticket": ticket,
        }, mode="stream")
        return result
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="stream")
        return result
    def GetOrderInfo(self, email: types.Email,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetOrderInfo", args={
            "email": email,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))