# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Email": types.Email,
    "stream_types.Email": stream_types.Email,

    "types.OrderInfo": types.OrderInfo,
    "stream_types.OrderInfo": stream_types.OrderInfo,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.TicketClassification": types.TicketClassification,
    "stream_types.TicketClassification": stream_types.TicketClassification,


    "types.SpamType": types.SpamType,

    "types.TicketLabel": types.TicketLabel,

}